### ISSUE TITLE
Using depreciated option for 1.23

### ISSUE THREAD

**Issue by hellreturn** [DaSchTour/Cavendish#16]
PHP Warning:  A skin using autodiscovery mechanism, Cavendish_old, was found in your skins/ directory. The mechanism will be removed in MediaWiki 1.25 and the skin will no longer be recognized. See https://www.mediawiki.org/wiki/Manual:Skin_autodiscovery for information how to fix this. [Called from Skin::getSkinNames in /home/xxxx/public_html/wiki/includes/Skin.php at line 74] in /home/xxxxx/public_html/wiki/includes/debug/Debug.php on line 303

**Comment by hellreturn** [comment]
Can you possibly post the fix for this? My apache error log is getting spammed like anything. Thanks

**Comment by SamanthaNguyen** [comment]
Fixed in the latest version of the skin.
