### ISSUE TITLE
Error with media wiki 1.25

### ISSUE THREAD

**Issue by hellreturn** [DaSchTour/Cavendish#18]
Getting below error while using Cavendish with media wiki 1.25.

I have "cavendish" folder under /skin/ directory and uploaded 3 php files and cavendish files under the cavendish folder and getting below error:

[Sat Aug 29 01:36:16 2015] [error] [] PHP Fatal error:  Uncaught exception 'Exception' with message '/home/xxxx/public_html/wiki/skins/cavendish/skin.json does not exist!' in /home/xxxx/public_html/wiki/includes/registration/ExtensionRegistry.php:79\nStack trace:\n#0 /home/xxxx/public_html/wiki/includes/GlobalFunctions.php(216): ExtensionRegistry->queue('/home/xxxx...')\n#1 /home/xxxx/public_html/wiki/LocalSettings.php(118): wfLoadSkin('cavendish')\n#2 /home/xxxx/public_html/wiki/includes/WebStart.php(124): require_once('/home/xxxx...')\n#3 /home/xxxx/public_html/wiki/index.php(38): require('/home/xxxx...')\n#4 {main}\n  thrown in /home/xxxx/public_html/wiki/includes/registration/ExtensionRegistry.php on line 79

**Comment by kflavin** [comment]
Same problem.

**Comment by ctrueden** [comment]
Instead of `wfLoadSkin`, use instead:
```
require_once "$IP/skins/Cavendish/Cavendish.php";
```

At least until #19 is merged.

**Comment by DaSchTour** [comment]
Should work after #20
