### ISSUE TITLE
VAR-SOM-6UL wiki page product information link does not work

### ISSUE THREAD

**Issue by Timo01** [DaSchTour/Cavendish#26]
On page
http://variwiki.com/index.php?title=VAR-SOM-6UL
the link "For more information on this product follow this link" does not work.
here is the link:
https://www.variscite.com/products/system-on-module-som/cortex-a7/var-som-6ul-freescale-imx-6ul

I need documenation of this product and I cant find it anywhere. Can you provide this datasheet as soon as possible or send it directly to my mail: timo.seppala@missing-link.fi

Thank you.
Best regards,
Timo Seppälä

**Comment by mary-kate** [comment]
You'll want to discuss with the people who run variwiki.com/variscite.com about that; this is merely the source code repository & issue tracker for the MediaWiki skin that variwiki.com happens to be using currently.
