### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by chmaculus** [DaSchTour/Cavendish#28]
/usr/bin/ld: cannot find -lrivwebcapi
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:628: addcart_test] Error 1
make[3]: *** Se espera a que terminen otras tareas....
make[3]: se sale del directorio '/mnt/sda6/descargas/radio software/2/rivendell/apis/rivwebcapi/tests'
make[2]: *** [Makefile:469: all-recursive] Error 1
make[2]: se sale del directorio '/mnt/sda6/descargas/radio software/2/rivendell/apis/rivwebcapi'
make[1]: *** [Makefile:422: all-recursive] Error 1
make[1]: se sale del directorio '/mnt/sda6/descargas/radio software/2/rivendell/apis'
make: *** [Makefile:518: all-recursive] Error 1

any idea?

**Comment by mary-kate** [comment]
This issue seems to be unrelated to the Cavendish MediaWiki skin, so closing.
