### ISSUE TITLE
Permission Docs not loading

### ISSUE THREAD

**Issue by Itssmartgamer** [DaSchTour/Cavendish#30]
Hi,
I am trying to use the essentials permission docs where you can search the permission. When I click on it, it brings me to the page and I don't type anything and it says 0 results. Then when I type in what I am looking for it says cant display on the table. I  have tried on multiple devices, on 3 networks do you know how to fix the issue.

**Comment by mary-kate** [comment]
This issue seems to be unrelated to the Cavendish MediaWiki skin, so closing.
