### ISSUE TITLE
Adding new fonts

### ISSUE THREAD

**Issue by DaSchTour** [DaSchTour/Cavendish#7]
Just to track branch new-fonts

**Comment by SamanthaNguyen** [comment]
@DaSchTour Just wondering, did you have any specific plans/ideas of which fonts you wanted to add to this skin?

**Comment by DaSchTour** [comment]
I started a branch called new-fonts back than and made some experiments. I added some OpenSans and Ubuntu Fonts there.

**Comment by SamanthaNguyen** [comment]
Thanks, I'll try and see if I can look into that :)

**Comment by DaSchTour** [comment]
It was just an idea 😉 so no worry about just closing it

**Comment by SamanthaNguyen** [comment]
Alright, thanks for the clarification :) I seem to multitask a lot these days anyways, so I might not actually have time to look at this; I'll just decline this task for now.
